### ISSUE TITLE
Setup failed for sleep_as_android: Integration not found.

### ISSUE THREAD

**Issue by hACKrus** [IATkachenko/HA-SleepAsAndroid#13]
After update to version 1.2.4 getting such error in logs:

```
Logger: homeassistant.setup
Source: setup.py:173
First occurred: 1:42:57 PM (1 occurrences)
Last logged: 1:42:57 PM

Setup failed for sleep_as_android: Integration not found.
```

In Integrations menu:

![image](https://user-images.githubusercontent.com/12397874/129555577-60c27caf-09a7-4a6c-9d46-263f94dec674.png)

If delete Integration - new will not presented in Add menu.

Sleep sensor exists, but with state: unavailable.

Revert to v1.2.3 fix the problem.

**Comment by Mikhail5555** [comment]
I also was looking at this, i think i found the reason, for the release no `sleep_as_android.zip` file is provided.

**Comment by IATkachenko** [comment]
oops... it was manual release so CI tools don't create archive... sorry.

**Comment by IATkachenko** [comment]
Archive was added to release. Is it OK now?

**Comment by Mikhail5555** [comment]
`[custom_components.hacs] <Integration IATkachenko/HA-SleepAsAndroid> Download of sleep_as_android.zip completed`

Seems indeed fixed! Thanks!

I'm kinda dissapointed in Hacs since it reported no error at all, it just failed to create a component in `/config/custom_component/sleep_as_android`, so was kinda annoying to debug.

**Comment by Mikhail5555** [comment]
You might also want to add it to the v2.0.0 beta (If you want people to be able to test it)

**Comment by IATkachenko** [comment]
@Mikhail5555, good point, thank you.
