### ISSUE TITLE
Update Blueprint To Allow Utilizing New Sensor Attributes.

### ISSUE THREAD

**Issue by MikeKMiller** [IATkachenko/HA-SleepAsAndroid#32]
# General information
Could I request an update to the Blueprint to allow entering a value for the the new attributes from [Issue 30](https://github.com/IATkachenko/HA-SleepAsAndroid/issues/30)

(specifically the Label attribute) 
When using the Blueprint to create an automation, to create a Condition based on the Label. For example, only run if the Label matches, or Run Except if the Label Matches.

**Comment by IATkachenko** [comment]
@MikeKMiller, hello.

How should we use attributes in blueprint? In condition part (like person state) or somewhere else?

Generally you may use "[choose](https://www.home-assistant.io/docs/scripts#choose-a-group-of-actions)" action for trigger and do different actions based on attribute

**Comment by MikeKMiller** [comment]
Yes I would suggest using it like the person state, as a Condition.

**Comment by IATkachenko** [comment]
It will not work in way like you expect: condition applied to all triggers, but not all triggers have attribute value and it will have attributes "unknown". So if you have automatization that require `label == foo`, then only action with defined label will be usable, because all others will have label `unknown`.

But it is possible to create second blueprint for triggers that have label attribute. It seems that we should work in this way.

**Comment by MikeKMiller** [comment]
Ok, I am completely ooen to what you think will work best.

**Comment by MikeKMiller** [comment]
yes thank you!!

**Comment by IATkachenko** [comment]
Welcome!
Will merge to master soon.

**Comment by IATkachenko** [comment]
Merged.
